GET http://localhost:3000/users/list
###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
   "name": "Jose Garcia",
   "email": "jbellorin@miu.edu",
   "password": "1234",
   "position": "student"
}
###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
   "name": "Asaad Saad",
   "email": "asaad@miu.edu",
   "password": "9999",
   "position": "professor"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username" : "Jose",
    "password" : "1234"
}