POST http://localhost:3000/api/professor/createexam
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzY5ODE5NjgsImV4cCI6MTYzNjk4MjU2OH0.CusD9u2lcg2g0ckyjomoPOJKKFZ5TwnOXYpSGprgwwg
###
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
   "name": "Nhatty Birhanu",
   "email": "najema@miu.edu",
   "password": "1234",
   "role": "student"
}
###
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
   "name": "Asaad Saad",
   "email": "asaad@miu.edu",
   "password": "9999",
   "role": "professor"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email" : "asaad@miu.edu",
    "password" : "9999"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "najema@miu.edu",
   "password": "1234"
}
###
GET http://localhost:3000/api/users/availability/email/najema@miu.edu
